
version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CoinDataService/CoinDataService.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output CoinDataService/CoinDataService.csproj
  post_build:
      commands:
      - printf '[{"name":"sample-app","imageUri":"httpd:2.4"}]' > imagedefinitions.json
artifacts:
  files:
    - CodeBuild-CoinDataService/build_output/**/*
    - scripts/**/*
    - appspec.yml
    - imagedefinitions.json
